remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

# Site Settings
title                    : "Bin-e's Algorithm"
#title_separator          : "-"
name                     : "Jeong-Uk Park"
description              : "Jeong-Uk's algorithm solving"
url                      : "https://algorithm.bin-e.dev"
baseurl                  : "/"
repository               : "https://github.com/bin-e/algorithm"

# Aux links for the upper right navigation
aux_links:
  "Go to repository":
    - "//github.com/bin-e/algorithm"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
